datasources:
  default:
    connection:
      url: ${MONGO_URL}
    objectFiles:
      - "./src/**"
public:
  cfs:
    store: local
    local:
      folder: storage
tenant:
  _id: ${STEEDOS_TENANT_ID}
  enable_register: true
  enable_forget_password: false
  saas: false
  enable_password_login: true
  enable_mobile_code_login: false
  enable_email_code_login: false
  enable_bind_mobile: false
sms:
  qcloud:
    smsqueue_interval: 1000
    sdkappid: ${STEEDOS_SMS_QCLOUD_SDKAPPID}
    appkey: ${STEEDOS_SMS_QCLOUD_APPKEY}
    signname: ${STEEDOS_SMS_QCLOUD_SIGNNAME}
email:
  from: ${MAIL_FROM}
  url: ${MAIL_URL}
plugins:
  - "@steedos/accounts"
  - "@steedos/app-crm"
  - "@steedos/app-contracts"
  - "@steedos/plugin-qywx"
  - "@steedos/plugin-enterprise"
cron:
  instancerecordqueue_interval: 10000
  mailqueue_interval: 10000
  push_interval: 1000
  webhookqueue_interval: 1000
